apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ledger-workload-hardening
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/YOUR_REPO.git
    targetRevision: main
    path: task-1-workload-hardening/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ledger
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
